import fs from "node:fs/promises";
import path from "node:path";

import { userPaths } from "./paths";

/**
 * The Screener writes `output/screen-{slug}-{num}.md` for every PDF generated by
 * the Recruiter pipeline. This helper finds that file for a given report number,
 * regardless of company slug (slugs can drift if a report's company name is edited).
 */
export async function readScreenerForReport(reportNum: string): Promise<string | null> {
  const padded = reportNum.padStart(3, "0");
  let entries: string[];
  try {
    entries = await fs.readdir(userPaths.outputDir);
  } catch {
    return null;
  }
  const match = entries.find(
    (f) => f.startsWith("screen-") && f.endsWith(`-${padded}.md`),
  );
  if (!match) return null;
  try {
    return await fs.readFile(path.join(userPaths.outputDir, match), "utf-8");
  } catch {
    return null;
  }
}
